# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/account_settings', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # AccountSetting. As you add validations to AccountSetting, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      AccountSetting.create! valid_attributes
      get account_settings_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      account_setting = AccountSetting.create! valid_attributes
      get account_setting_url(account_setting)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_account_setting_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      account_setting = AccountSetting.create! valid_attributes
      get edit_account_setting_url(account_setting)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new AccountSetting' do
        expect do
          post account_settings_url, params: { account_setting: valid_attributes }
        end.to change(AccountSetting, :count).by(1)
      end

      it 'redirects to the created account_setting' do
        post account_settings_url, params: { account_setting: valid_attributes }
        expect(response).to redirect_to(account_setting_url(AccountSetting.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new AccountSetting' do
        expect do
          post account_settings_url, params: { account_setting: invalid_attributes }
        end.not_to change(AccountSetting, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post account_settings_url, params: { account_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested account_setting' do
        account_setting = AccountSetting.create! valid_attributes
        patch account_setting_url(account_setting), params: { account_setting: new_attributes }
        account_setting.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the account_setting' do
        account_setting = AccountSetting.create! valid_attributes
        patch account_setting_url(account_setting), params: { account_setting: new_attributes }
        account_setting.reload
        expect(response).to redirect_to(account_setting_url(account_setting))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        account_setting = AccountSetting.create! valid_attributes
        patch account_setting_url(account_setting), params: { account_setting: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested account_setting' do
      account_setting = AccountSetting.create! valid_attributes
      expect do
        delete account_setting_url(account_setting)
      end.to change(AccountSetting, :count).by(-1)
    end

    it 'redirects to the account_settings list' do
      account_setting = AccountSetting.create! valid_attributes
      delete account_setting_url(account_setting)
      expect(response).to redirect_to(account_settings_url)
    end
  end
end
