# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/channel_members', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ChannelMember. As you add validations to ChannelMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ChannelMember.create! valid_attributes
      get channel_members_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      channel_member = ChannelMember.create! valid_attributes
      get channel_member_url(channel_member)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_channel_member_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      channel_member = ChannelMember.create! valid_attributes
      get edit_channel_member_url(channel_member)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ChannelMember' do
        expect do
          post channel_members_url, params: { channel_member: valid_attributes }
        end.to change(ChannelMember, :count).by(1)
      end

      it 'redirects to the created channel_member' do
        post channel_members_url, params: { channel_member: valid_attributes }
        expect(response).to redirect_to(channel_member_url(ChannelMember.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ChannelMember' do
        expect do
          post channel_members_url, params: { channel_member: invalid_attributes }
        end.not_to change(ChannelMember, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post channel_members_url, params: { channel_member: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested channel_member' do
        channel_member = ChannelMember.create! valid_attributes
        patch channel_member_url(channel_member), params: { channel_member: new_attributes }
        channel_member.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the channel_member' do
        channel_member = ChannelMember.create! valid_attributes
        patch channel_member_url(channel_member), params: { channel_member: new_attributes }
        channel_member.reload
        expect(response).to redirect_to(channel_member_url(channel_member))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        channel_member = ChannelMember.create! valid_attributes
        patch channel_member_url(channel_member), params: { channel_member: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested channel_member' do
      channel_member = ChannelMember.create! valid_attributes
      expect do
        delete channel_member_url(channel_member)
      end.to change(ChannelMember, :count).by(-1)
    end

    it 'redirects to the channel_members list' do
      channel_member = ChannelMember.create! valid_attributes
      delete channel_member_url(channel_member)
      expect(response).to redirect_to(channel_members_url)
    end
  end
end
