# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/chat_channels', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # ChatChannel. As you add validations to ChatChannel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ChatChannel.create! valid_attributes
      get chat_channels_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      chat_channel = ChatChannel.create! valid_attributes
      get chat_channel_url(chat_channel)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_chat_channel_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      chat_channel = ChatChannel.create! valid_attributes
      get edit_chat_channel_url(chat_channel)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ChatChannel' do
        expect do
          post chat_channels_url, params: { chat_channel: valid_attributes }
        end.to change(ChatChannel, :count).by(1)
      end

      it 'redirects to the created chat_channel' do
        post chat_channels_url, params: { chat_channel: valid_attributes }
        expect(response).to redirect_to(chat_channel_url(ChatChannel.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ChatChannel' do
        expect do
          post chat_channels_url, params: { chat_channel: invalid_attributes }
        end.not_to change(ChatChannel, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post chat_channels_url, params: { chat_channel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested chat_channel' do
        chat_channel = ChatChannel.create! valid_attributes
        patch chat_channel_url(chat_channel), params: { chat_channel: new_attributes }
        chat_channel.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the chat_channel' do
        chat_channel = ChatChannel.create! valid_attributes
        patch chat_channel_url(chat_channel), params: { chat_channel: new_attributes }
        chat_channel.reload
        expect(response).to redirect_to(chat_channel_url(chat_channel))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        chat_channel = ChatChannel.create! valid_attributes
        patch chat_channel_url(chat_channel), params: { chat_channel: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested chat_channel' do
      chat_channel = ChatChannel.create! valid_attributes
      expect do
        delete chat_channel_url(chat_channel)
      end.to change(ChatChannel, :count).by(-1)
    end

    it 'redirects to the chat_channels list' do
      chat_channel = ChatChannel.create! valid_attributes
      delete chat_channel_url(chat_channel)
      expect(response).to redirect_to(chat_channels_url)
    end
  end
end
