# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/social_accounts', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SocialAccount. As you add validations to SocialAccount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      SocialAccount.create! valid_attributes
      get social_accounts_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      social_account = SocialAccount.create! valid_attributes
      get social_account_url(social_account)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_social_account_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      social_account = SocialAccount.create! valid_attributes
      get edit_social_account_url(social_account)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new SocialAccount' do
        expect do
          post social_accounts_url, params: { social_account: valid_attributes }
        end.to change(SocialAccount, :count).by(1)
      end

      it 'redirects to the created social_account' do
        post social_accounts_url, params: { social_account: valid_attributes }
        expect(response).to redirect_to(social_account_url(SocialAccount.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new SocialAccount' do
        expect do
          post social_accounts_url, params: { social_account: invalid_attributes }
        end.not_to change(SocialAccount, :count)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post social_accounts_url, params: { social_account: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested social_account' do
        social_account = SocialAccount.create! valid_attributes
        patch social_account_url(social_account), params: { social_account: new_attributes }
        social_account.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the social_account' do
        social_account = SocialAccount.create! valid_attributes
        patch social_account_url(social_account), params: { social_account: new_attributes }
        social_account.reload
        expect(response).to redirect_to(social_account_url(social_account))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        social_account = SocialAccount.create! valid_attributes
        patch social_account_url(social_account), params: { social_account: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested social_account' do
      social_account = SocialAccount.create! valid_attributes
      expect do
        delete social_account_url(social_account)
      end.to change(SocialAccount, :count).by(-1)
    end

    it 'redirects to the social_accounts list' do
      social_account = SocialAccount.create! valid_attributes
      delete social_account_url(social_account)
      expect(response).to redirect_to(social_accounts_url)
    end
  end
end
